### DISCUSSION TITLE
Workers Types Generator should generate env vars type as string

### DISCUSSION THREAD

**Discussion by msisdev** [cloudflare/workerd#2337] [Ideas]
## Current situation
Currently `wrangler types`  makes env vars type as concrete value. (using wrangler 3.62.0)

For example, this configuration
```toml
# wrangler.toml
[vars]
MY_VARIABLE = "production_value"
```
will be:
```ts
// worker-configuration.d.ts
interface Env {
  MY_VARIABLE: "production_value";
}
```

## Problem
When I want to set different values to each environment like,
```toml
# wrangler.toml
[vars]
WHICH_ENV = "development"

[env.preview.vars]
WHICH_ENV = "preview"

[env.production.vars]
WHICH_ENV = "production"
```
it generates
```ts
// worker-configuration.d.ts
interface Env {
  WHICH_ENV: "development";
}
```
and I can't compare the value in typescript code.
```ts
// compile error
export function createSession(env: Env) {
    switch (env.WHICH_ENV) {
        case "development":
        case "preview":
            return createMemorySessionStorage({ cookie: sessionCookie })        

        case "production":
        default:
            return createKVSessionStorage(env.KV_SESSION)
    }
}
```

## Suggestion
So `wrangler types` command should generate env vars type as string.

## Importance of the problem?
It is not quite a problem, because I can still manually change the type in `worker-configuration.d.ts`.

But I think making env vars comparable is intuitive and just right.
