### ISSUE TITLE
libsodium-wrapper reports "No secure random number generator found"

### ISSUE THREAD

**Issue by caoster** [cloudflare/workerd#1418]
Here is a minimal working example:
```javascript
// src/index.js
import 'node:crypto';
import _sodium from 'libsodium-wrappers';

globalThis.window = undefined;
globalThis.importScripts = undefined;

export default {
	async fetch(request) {
		globalThis.window = undefined;
		globalThis.importScripts = undefined;

		await _sodium.ready;
		return new Response('Hello');
	}
};
```

```toml
# wrangler.toml
name = "test"
main = "src/index.js"
compatibility_date = "2023-10-25"
compatibility_flags = [ "nodejs_compat" ]
env = { }
```

According to the [issue](https://github.com/cloudflare/miniflare/issues/308) at miniflare, it should work with `wrangler dev`. However, it keeps reporting **Both wasm and asm failed to loadNo secure random number generator found** at `(.../node_modules/libsodium-wrappers/dist/modules/libsodium-wrappers.js:1:16026)` no matter how I modify the version of wrangler (with "compatibility_date" in .toml) and libsodium.

This code works neither on my computer nor with Cloudflare workers.

---

System information
```
Apple M2 chip
macOS Sonoma 14.1.1 (23B81)
npm: '10.2.0'
node: '21.1.0'
wrangler 3.15.0 
```
