### ISSUE TITLE
How does `workerd` introduce `d1` database configuration

### ISSUE THREAD

**Issue by dairoot** [cloudflare/workerd#2309]
How does `workerd` introduce `d1` database configuration
```toml
[[d1_databases]]
binding = "DB" 
database_name = "xxxx"
database_id = "xx-f6b5-xx-a19b-xxxx"
```

```capnp
using Workerd = import "/workerd/workerd.capnp";

const helloWorldExample :Workerd.Config = (
  sockets = [ ( name = "http", address = "*:8787", http = (), service = "main" ) ]
);


const helloWorld :Workerd.Worker = (
  modules = [
    (name = "worker", esModule = embed "dist/index.js")
  ],
  compatibilityDate = "2024-06-10",

  bindings = [
    (name = "ADMIN_USERNAME", text = "xxxxx"),
    (name = "ADMIN_PASSWORD", text = "xxxxx2"),
    (name = "DEBUG", text = "true" ),
  ],

);
```
