### ISSUE TITLE
clang-17 failed: error executing CppLink command

### ISSUE THREAD

**Issue by willswire** [cloudflare/workerd#3247]
I am trying to contribute `workerd` as a package to WolfiOS [here](https://github.com/wolfi-dev/os/pull/37076). I've included the necessary build dependencies:

```yaml
environment:
  contents:
    packages:
      - bash
      - bazelisk
      - bazelisk-default
      - binutils
      - build-base
      - busybox
      - clang-17
      - clang-17-dev
      - gnutar
      - libtool
      - llvm-libunwind-17
      - llvm-libcxx-17
      - llvm-libcxx-17-dev
      - llvm-libcxxabi-17
      - llvm-lld-17
      - llvm17
      - llvm17-dev
      - posix-libc-utils
      - python3-dev
      - tcl
```

However I am getting the following error:

```
ERROR: /home/build/.cache/bazel/_bazel_root/79a1bfc8c8b5b6a6d226b38d072f165b/external/capnp-cpp/src/capnp/BUILD.bazel:139:10: Linking external/capnp-cpp/src/capnp/capnpc-c++ [for tool] failed: (Exit 1): clang-17 failed: error executing CppLink command (from target @@capnp-cpp//src/capnp:capnpc-c++)
```

Potentially related issues:
- https://github.com/cloudflare/workerd/issues/1689
- https://github.com/bazelbuild/bazel/issues/24486
