### ISSUE TITLE
🐛 Bug Report — `getPlatformProxy` invariant behavior with RPC targets

### ISSUE THREAD

**Issue by hntrl** [cloudflare/workerd#3713]
```
@cloudflare/workers-types 4.20250311.0
wrangler 3.114.1
```

In local dev, I'm trying to access a method on an rpc target through a service binding that's defined on another worker using `getPlatformProxy`, but i'm running into some invariant behaviors when accessing the target. If I try to call a method on the target using the proxy, I get an unexpected TypeError. I'm able to access the method in the way I'm describing if I'm using it on a separate worker with the same bindings and run it using `wrangler dev`.

I've detailed my setup as best as I can in this issue, but I also have a repro [here](https://github.com/hntrl/durable-object-rpc-repro/tree/platform-proxy-issue).

**workerA**
---
```toml
# workerA/wrangler.toml

#:schema node_modules/wrangler/config-schema.json
name = "durable-object-repro-a"
main = "src/worker.ts"
compatibility_date = "2024-12-18"
```
```ts
// workerA/src/worker.ts

import { RpcTarget, WorkerEntrypoint } from "cloudflare:workers";

class FooTarget extends RpcTarget {
  async getFoo() {
    return "foo";
  }
}

export default class WorkerA extends WorkerEntrypoint<Env> {
  get foo() {
    return new FooTarget();
  }
  getBar() {
    return "bar";
  }
}
```

**local**
---
```toml
# local/wrangler.toml

#:schema node_modules/wrangler/config-schema.json
name = "durable-object-repro-local"
compatibility_date = "2024-11-18"
main = "src/index.ts"

services = [{ binding = "WORKER_A", service = "durable-object-repro-a" }]
```
```ts
// local/src/index.ts

// @ts-nocheck

import { getPlatformProxy } from "wrangler";

async function main() {
  const proxy = await getPlatformProxy();

  console.log(await proxy.env.WORKER_A.foo);
  // [Function: foo]

  console.log(await proxy.env.WORKER_A.getBar());
  // "bar"

  console.log(await proxy.env.WORKER_A.foo.getFoo());
  // TypeError: proxy.env.WORKER_A.foo.getFoo is not a function
}

main();
```
